# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{pedantic}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Pat Allan"]
  s.date = %q{2010-02-08}
  s.description = %q{Pares text down to the words that matter}
  s.email = %q{pat@freelancing-gods.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.textile"
  ]
  s.files = [
    "LICENSE",
     "README.textile",
     "lib/pedantic.rb",
     "lib/pedantic/emoticons.rb",
     "lib/pedantic/emphasis.rb",
     "lib/pedantic/html.rb",
     "lib/pedantic/punctuation.rb",
     "lib/pedantic/stems.rb",
     "lib/pedantic/txt.rb",
     "lib/pedantic/unimportant.rb",
     "lib/pedantic/uris.rb"
  ]
  s.homepage = %q{http://github.com/freelancing-god/pedantic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Text Cleaner}
  s.test_files = [
    "spec/pedantic/emoticons_spec.rb",
     "spec/pedantic/emphasis_spec.rb",
     "spec/pedantic/html_spec.rb",
     "spec/pedantic/punctuation_spec.rb",
     "spec/pedantic/stems_spec.rb",
     "spec/pedantic/txt_spec.rb",
     "spec/pedantic/unimportant_spec.rb",
     "spec/pedantic/uris_spec.rb",
     "spec/pedantic_spec.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<stemmer>, [">= 1.0.1"])
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<yard>, [">= 0"])
    else
      s.add_dependency(%q<stemmer>, [">= 1.0.1"])
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<yard>, [">= 0"])
    end
  else
    s.add_dependency(%q<stemmer>, [">= 1.0.1"])
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<yard>, [">= 0"])
  end
end

